[project]
name = "comfyui-daam-pack"
description = """Interactive tag attention explorer (SDXL only)
Click a spot in the image → the related tag
Click a tag → the related part of the image"""

version = "1.0.1"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = []

[project.urls]
Repository = "https://github.com/alchemine/comfyui-daam-pack"
"Bug Tracker" = "https://github.com/alchemine/comfyui-daam-pack/issues"

[tool.comfy]
PublisherId = "alchemine"
DisplayName = "ComfyUI-DAAM-Pack"
Icon = ""
